name: Environment variables and secrets
on: workflow_dispatch
env:
  MY_ENV_VAR: ${{ vars.MY_VAR || 'my-var-default' }}
  MY_ENV_SECRET: ${{ secrets.MY_SECRET }}
jobs:
  do-the-job:
    runs-on: ubuntu-latest
    steps:
      - name: output variable
        run: |
          echo 'MY_ENV_VAR: ${{ env.MY_ENV_VAR }}'
          if [ "${{env.MY_ENV_SECRET}}" = "abc" ]; then
            echo 'secret has correct value'
          fi
