name: Memory 1
on: workflow_dispatch
env:
  MY_VAR: ${{ vars.MY_VAR || 'var-default-value' }}
  MY_SECRET: ${{ secrets.MY_SECRET }}
jobs:
  do-the-job:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Output variable and secret
        run: |
          echo "${{ env.MY_VAR }}"
          if [ "${{ env.MY_SECRET }}" = "abc" ]; then
            echo "secret has correct value"
          fi